---
- name: Create group
  group: name={{ group }} state=present

- name: Ensure sudoers.d is enabled
  lineinfile: dest=/etc/sudoers state=present backup=yes regexp='^#includedir /etc/sudoers.d' line='#includedir /etc/sudoers.d'

- name: Set up password-less sudo for user
  copy: content="%{{ user }} ALL=(ALL) NOPASSWD:ALL" dest="/etc/sudoers.d/{{ user }}" owner=root group=root mode=0440

- name: Create user
  user: name={{ user }} state=present group={{ group }} shell=/bin/bash

- stat: path=/tmp
  register: t

- name: Take ownership of /tmp
  shell: sudo chown {{ user }}:{{ group }} /tmp
  when: take_ownership_of_tmp == "true" and t.stat.pw_name != "{{ user }}"
